import {
  AiCodeReviewProvider,
  ChatRequest,
  ChatResponseListener,
  ChatResponse,
  Conversation,
  ConversationTurn,
  Models,
  Actions,
  ContextItemType,
} from '../../../polygerrit-ui/app/api/ai-code-review'

export class HardcodedAiCodeReviewProvider implements AiCodeReviewProvider {
  constructor() {
    console.log('Hardcoded AI Provider initialized');
  }

  chat(req: ChatRequest, listener: ChatResponseListener): void {
    console.log('Received chat request:', req);

    // Emit a dummy streaming response in two chunks
    listener.emitResponse({
      response_parts: [
        {
          id: 1,
          text: "Analyzing the change...\n",
        },
      ],
      references: [],
      citations: [],
    });

    setTimeout(() => {
      const secondChunk: ChatResponse = {
        response_parts: [
          {
            id: 2,
            text:
                "This is a hardcoded AI response. No backend call was made.\n" +
                "Everything you see is generated by the demo provider.",
          },
        ],
        references: [],
        citations: [],
      };
      listener.emitResponse(secondChunk);
      listener.done();
    }, 600);
  }

  async listChatConversations(): Promise<Conversation[]> {
    return [
      {
        id: 'demo-conv-1',
        title: 'Hardcoded Conversation',
        timestamp_millis: Date.now(),
      },
    ];
  }

  async getChatConversation(): Promise<ConversationTurn[]> {
    return [
      {
        user_input: {user_question: 'Show me a demo'},
        response: {
          response_parts: [
            {id: 1, text: 'This is a previous hardcoded response.'},
          ],
          references: [],
          citations: [],
        },
        timestamp_millis: Date.now(),
      },
    ];
  }

  async getModels(): Promise<Models> {
    return {
      default_model_id: 'demo-model',
      models: [
        {
          model_id: 'demo-model',
          short_text: 'Demo Model',
          full_display_text: 'Demo Local Model (Hardcoded)',
        },
      ],
    };
  }

  async getActions(): Promise<Actions> {
    return {
      default_action_id: 'review',
      actions: [
        {
          id: 'review',
          display_text: 'AI Review',
          hover_text: 'Run a hardcoded AI review',
          enable_splash_page_card: false,
          enable_send_without_input: false,
          initial_user_prompt: 'Please analyze this change.',
        },
      ],
    };
  }

  async getContextItemTypes(): Promise<ContextItemType[]> {
    return [
      {
        id: 'demo-file',
        name: 'Demo File',
        icon: 'draft',
        regex: /file:\/\/.*/i,
        placeholder: 'file://path/to/file',
        parse(input: string) {
          if (!input.startsWith('file://')) return undefined;
          return {
            type_id: this.id,
            link: input,
            title: input.replace('file://', ''),
          };
        },
      },
    ];
  }
}
